### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by andrewaarestad** [Aaron-Bird/rubiks-cube#2]
I don't see that there's any license specified for this code.  Is that intentional, or did you mean to use an open source license?  I'd love to build off of this code, it's great!

**Comment by andrewaarestad** [comment]
cc @Aaron-Bird - can you let me know if the licensing is intentional?

**Comment by vmiklos** [comment]
@Aaron-Bird ping, could you please state the license of this repo? Three.js is MIT, do you publish under the same terms? Thanks :-)

**Comment by Aaron-Bird** [comment]
Added MIT license

**Comment by vmiklos** [comment]
Thanks!
